apis:
  pokeapi: 
    root: openapi/openapi.json
extends:
  - recommended
rules:
  tag-description: off
  operation-summary: off
  no-unresolved-refs: error
  no-unused-components: error
  operation-2xx-response: error
  operation-4xx-response: off
  operation-operationId: error
  operation-singular-tag: error
  no-enum-type-mismatch: error
  no-identical-paths: error
  no-ambiguous-paths: error
telemetry: off